#
#   TODO - Make this a real one when needed. 
#   Was going to do for HeroesDataUploader, but did manual DB setup
#


name: Migrate Data to MongoDB

on:
  push:
    branches:
      - your-target-branch  # Replace with your specific branch name

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Migration
        run: dotnet run --project HeroesDataUploader/HeroesDataUploader.csproj
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          MONGO_DATABASE_NAME: ${{ secrets.MONGO_DATABASE_NAME }}
