name: NotificateDiscord

on:
  workflow_run:
    workflows: [ "Deploy" ]
    types:
      - completed

jobs:
  build:
    name: Sending message to Discord
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: ${{ github.event_name }} Triggered. A new version of the API has been deployed to Render.