name: notificate-discord.yml
on:
  workflow_run:
    workflows: [ "Deploy" ]
    types:
      - completed

jobs:
  steps:
    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: ${{ github.event_name }} Triggered. A new version of the API has been deployed to Render.